server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hyojinbae-sample/hyojinbae-spring-cloud-sample-config-repo
management:
  security:
    enabled: false
encrypt:
  key-store:
    location: file:${user.home}/server.jks # path for windows?
    password: letmein
    alias: mytestkey
    secret: changeme
